[tox]
minversion = 4.2
envlist =
  mypy
  unit-tests

[defs]
pyfiles =
  rel/

[testenv:mypy]
tags =
  check
deps =
  -r requirements/testenv-mypy.txt
commands =
  mypy {[defs]pyfiles}

[testenv:unit-tests]
tags =
  tests
deps =
  -r requirements/testenv-unit-tests.txt
commands =
  pytest --strict {posargs} -- rel/test.py
