from collections.abc import Callable
from typing import Any, IO, Self
from _typeshed import Incomplete

from .registrar import Registrar

Channel = IO[bytes]

EV_PERSIST: int
EV_READ: int
EV_SIGNAL: int
EV_TIMEOUT: int
EV_WRITE: int
noadd: str

def contains(mode: int, bit: int) -> bool: ...

class Event:
    registrar: Registrar
    cb: Callable[[Self, int, int], Any]
    arg: Any
    timeout: Timer
    evtype: int
    handle: int
    children: Incomplete
    def __init__(self, registrar: Registrar, cb: Callable[[Self, int, int, Any], Any], arg: Any, evtype: int, handle: int) -> None: ...
    def spawn_children(self) -> None: ...
    def add(self, delay: Incomplete | None = ...) -> None: ...
    def delete(self) -> None: ...
    def pending(self) -> int: ...
    def callback(self) -> None: ...

class SocketIO:
    registrar: Registrar
    evtype: int
    sock: Channel
    fd: int
    cb: Callable[..., bool]
    args: list[Any]
    persist: bool
    active: int
    timeout: Timer
    def __init__(self, registrar: Registrar, evtype: int, sock: Channel, cb: Callable[..., bool], *args: Any) -> None: ...
    def persistent(self) -> None: ...
    def add(self, delay: float | None = ...) -> None: ...
    def delete(self) -> None: ...
    def dereference(self) -> None: ...
    def pending(self) -> int: ...
    def callback(self) -> None: ...

class Signal:
    registrar: Registrar
    sig: int
    default: Incomplete
    cb: Callable[..., Any]
    args: list[Any]
    timeout: Incomplete
    def __init__(self, registrar: Registrar, sig: int, cb: Callable[..., Any], *args: Any) -> None: ...
    active: int
    def add(self, delay: float | None = ...) -> None: ...
    def delete(self) -> None: ...
    def reset(self) -> None: ...
    def pending(self) -> int: ...
    def callback(self, *args: Any) -> None: ...

class Timer:
    registrar: Registrar
    cb: Callable[..., Any]
    args: list[Any]
    def __init__(self, registrar: Registrar, delay: float, cb: Callable[..., bool], *args: Any) -> None: ...
    delay: float | None
    expiration: float | None
    def add(self, delay: float | None = ...) -> None: ...
    def delete(self, dereference: bool = ...) -> None: ...
    def pending(self) -> int: ...
    def check(self, t: float | None = ...) -> bool: ...
