from collections.abc import Callable
import select
from typing import Any
from _typeshed import Incomplete

from .errors import AbortBranch as AbortBranch
from .listener import Channel, Event as Event, Signal as Signal, SocketIO as SocketIO, Timer as Timer, contains as contains

LISTEN_KQUEUE: int
LISTEN_SELECT: int
LISTEN_POLL: int
SLEEP_SEC: float
SLEEP_TURBO: float
SEL_MAX_FD: int

def set_sleep(s: float) -> None: ...
def set_turbo(s: float) -> None: ...
def kbint(signals: set[int]) -> bool: ...

class Registrar:
    events: dict[str, dict[int, SocketIO]]
    timers: set[Timer]
    ordered_timers: list[Timer]
    signals: set[Signal]
    tick: int
    run_dispatch: bool
    error_check: bool
    def __init__(self) -> None: ...
    def report(self) -> dict[str, int]: ...
    def signal_add(self, sig: Signal) -> None: ...
    def signal_remove(self, sig: Signal) -> None: ...
    def init(self) -> None: ...
    def event(self, callback: Callable[[], None], arg: Incomplete | None, evtype: int, handle: Incomplete | None) -> Event: ...
    def read(self, sock: Channel, cb: Callable[..., None], *args: Any) -> SocketIO: ...
    def write(self, sock: Channel, cb: Callable[..., None], *args: Any) -> SocketIO: ...
    def error(self, sock: Channel, cb: Callable[..., None], *args: Any) -> SocketIO: ...
    def dispatch(self) -> None: ...
    def loop(self) -> bool | Signal: ...
    def abort(self) -> None: ...
    def abort_branch(self) -> None: ...
    def signal(self, sig: int, callback: Callable[..., None], *args: Any) -> Signal: ...
    def timeout(self, delay: int, cb: Callable[..., None], *args: Any) -> Timer: ...
    def add_timer(self, timer: Timer) -> None: ...
    def remove_timer(self, timer: Timer) -> None: ...
    def check_timers(self) -> bool: ...
    def callback(self, etype: str, fd: int) -> None: ...
    def handle_error(self, fd: int) -> None: ...
    def handle_error_nah(self, fd: int) -> None: ...

class KqueueRegistrar(Registrar):
    kq: Incomplete
    kqf: dict[str, int]
    def __init__(self) -> None: ...
    def abort(self) -> None: ...
    def add(self, event: Event) -> None: ...
    def remove(self, event: Event) -> None: ...
    def check_events(self) -> bool: ...

class SelectRegistrar(Registrar):
    def __init__(self) -> None: ...
    def add(self, event: Event) -> None: ...
    def remove(self, event: Event) -> None: ...
    def do_check(self, rlist: list[int], wlist: list[int]) -> bool: ...
    def check_events(self) -> bool: ...

class PollRegistrar(Registrar):
    poll: Incomplete
    def __init__(self) -> None: ...
    def add(self, event: Event) -> None: ...
    def remove(self, event: Event) -> None: ...
    def check_events(self) -> bool: ...
    def register(self, fd: int) -> None: ...

class EpollRegistrar(PollRegistrar):
    poll: Incomplete
    def __init__(self) -> None: ...
