from collections.abc import Callable
from typing import Any, IO, SupportsIndex
from _typeshed import Incomplete

from .listener import EV_PERSIST as EV_PERSIST, EV_READ as EV_READ, EV_SIGNAL as EV_SIGNAL, EV_TIMEOUT as EV_TIMEOUT, EV_WRITE as EV_WRITE, Channel, Event, Signal, SocketIO, Timer
from .registrar import EpollRegistrar as EpollRegistrar, KqueueRegistrar as KqueueRegistrar, PollRegistrar as PollRegistrar, SelectRegistrar as SelectRegistrar, Registrar, set_sleep as set_sleep, set_turbo as set_turbo

def override() -> None: ...

running: bool
registrar: Incomplete
threader: Incomplete
verbose: bool
supported_methods: Incomplete
mapping: Incomplete

def log(text: str) -> None: ...

class Thread_Checker:
    active: Incomplete
    def __init__(self, threaded: bool) -> None: ...
    checker: Incomplete
    sleeper: Incomplete
    def go(self) -> None: ...
    def stop(self) -> None: ...
    def release(self, *args: Any) -> bool: ...
    def check(self) -> bool: ...

def check_init() -> None: ...
def get_registrar(method: str) -> Registrar: ...
def set_verbose(isverb: bool) -> None: ...
def initialize(methods: list[str] = ..., options: tuple[str] | list[str] = ...) -> str: ...

SAFE_READ: bool

def safe_read() -> None: ...
def read(sock: Channel, cb: Callable[..., bool], *args: Any) -> SocketIO: ...
def write(sock: Channel, cb: Callable[..., bool], *args: Any) -> SocketIO: ...
def error(sock: Channel, cb: Callable[..., bool], *args: Any) -> SocketIO: ...
def timeout(delay: int, cb: Callable[..., bool], *args: Any) -> Timer: ...
def signal(sig: int, callback: Callable[..., Any], *args: Any) -> Signal: ...
def dispatch() -> None: ...
def loop() -> None: ...
def report() -> dict[str, int]: ...
def is_running() -> bool: ...
def abort() -> None: ...
def abort_branch() -> None: ...
def init() -> None: ...
def event(callback: Callable[[], bool], arg: Incomplete | None = ..., evtype: int = ..., handle: Incomplete | None = ...) -> Event: ...
def thread(callback: Callable[[], bool]) -> None: ...
def tick() -> SupportsIndex: ...
def start() -> None: ...
def stop() -> None: ...
