from _typeshed import Incomplete

def notice(*lines: str) -> None: ...
def exit() -> None: ...
def error(msg: str, *lines: str) -> None: ...

RT_MEDIA: Incomplete
RT_USAGE: Incomplete

class Timer:
    count: int
    goal: Incomplete
    media: Incomplete
    def __init__(self, s: int, m: int, h: int, interval: int = ..., mediapath: str=...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def update(self) -> bool: ...
    def alarm(self) -> None: ...

def timerCLI() -> None: ...
