from collections.abc import Callable
from typing import Any
from _typeshed import Incomplete

from .listener import Channel, Event

listeners: Incomplete
happenings: Incomplete

def emit(channel: Channel, *args: Any, **kwargs: Any) -> None: ...
def ask(channel: Channel, *args: Any, **kwargs: Any) -> Any: ...
def listen(channel: Channel, cb: Callable[..., Any]) -> None: ...
def when(event: Event, cb: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
def transpire(event: Event) -> None: ...
